### ISSUE TITLE
Ephemeral colors overlapping, preventing you from reading text (V2 issue)

### ISSUE THREAD

**Issue by p0t4t0sandwich** [B4T3S/Fallout4TerminalTheme#28]
Back at it again, this is something I noticed while working on one of my bots:
![image](https://user-images.githubusercontent.com/82551072/225820754-16342fef-4d3f-495c-9e94-faeab08821a3.png)

I could be talking out my arse, but you could take the same approach as V1 and just leave it as the normal blue tint/overlay.

**Comment by CommandCrafterHD** [comment]
Yeah that issue is *somewhat* known, I've got a fix planned I just need to sit down and implement it ^^

**Comment by axcyia** [comment]
i'm still having this issue, has the fix been rolled out yet or is it still yet to be implemented??

**Comment by MichaeIDeSanta** [comment]
> Yeah that issue is _somewhat_ known, I've got a fix planned I just need to sit down and implement it ^^

something else that may help a little bit, this is the message i get after i stay too much afk on voice alone (bc i have no friends)
![image](https://github.com/CommandCrafterHD/Fallout4TerminalTheme/assets/62386198/f59c7455-9196-44c9-acf1-e98638e3d273)
